version: "2"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/app
    expose:
      - "50078"
    # In order for the npm i command to work, we need to make the proto
    # file publically available or figure out another way to allow the container
    # to read the file (preferably not through ssh w/ git)
    command: bash -c "npm i && npm start"
