# we need to use DC v2 in order to support `extends` which is not supperted
# by Version 3 yet (https://github.com/moby/moby/issues/31101)
version: '2'

services:
  # Kinesis Relayer
  relayer:
    container_name: 'relayer'
    image: 'node:8'
    working_dir: '/home/app'
    volumes:
      - './:/home/app'
      - 'secure:/secure/'
    depends_on:
      - mongo
      - redis
      - lnd_btc
    environment:
      - GRPC_HOST=0.0.0.0
      - GRPC_PORT=50078
      # - GRPC_VERBOSITY=INFO
      # - GRPC_TRACE=all
      - MONGODB_CONNECTION_URL=mongodb://mongo/relayer
      - LND_URL=lnd_btc:10009
      - TLS_PATH=/secure/tls.cert
      - MACAROON_PATH=/secure/admin.macaroon
      - REDIS_HOST=redis
      - GRPC_SSL_CIPHER_SUITES=HIGH+ECDSA
    ports:
      - '50078:50078'
    networks:
      - relayer
      - btcd
    command: bash -c 'npm i && npm start'

  # Mongo DB
  mongo:
    image: 'mongo:3.6.3'
    working_dir: '/home/db'
    ports:
      - '27017:27017'
    networks:
      - relayer

  # Redis
  redis:
    image: redis:4.0.9-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      - relayer


  # Extensions of the official LND docker build found here:
  #
  btc:
    extends:
      file: ./docker/docker-compose.yml
      service: btc
    networks:
      - btcd

  btcd:
    extends:
      file: ./docker/docker-compose.yml
      service: btcd
    networks:
      btcd:
        aliases:
          - blockchain
          - rpcserver

  # We were missing a few containers from the LND file because we could not use
  # extends w/ links, so we decided to port btcctl/lnd_btc containers over.
  #
  # This node is here so we can create blocks for our fake simnet
  btcctl:
    extends: btc
    entrypoint: ["./start-btcctl.sh"]
    networks:
      - btcd

  # This is the btc node that relayer will interact with for the LND Engine
  lnd_btc:
    extends:
      file: ./docker/docker-compose.yml
      service: lnd
    networks:
      - btcd
    environment:
      - GRPC_VERBOSITY=DEBUG
      - GRPC_TRACE=all
    expose:
      - '8080'
      - '10009'
    volumes:
      - 'secure:/secure/'
    command: chmod a+rx /secure/admin.macaroon

# This information was taken from the LND docker setup (found in ./docker)
#
volumes:
  redis-data:
  secure:
  shared:
  bitcoin:

networks:
  relayer:
  btcd:
