version: '3'

services:
  # Kinesis Relayer
  relayer:
    container_name: 'relayer'
    image: 'node:8'
    working_dir: '/home/app'
    volumes:
      - './:/home/app'
      - 'secure:/secure/'
    depends_on:
      - mongo
      - redis
      - lnd_btc
    environment:
      - NODE_PATH=.
      - GRPC_HOST=0.0.0.0
      - GRPC_PORT=50078
      # - GRPC_VERBOSITY=INFO
      # - GRPC_TRACE=all
      - MONGODB_CONNECTION_URL=mongodb://mongo/relayer
      - LND_URL=lnd_btc:10009
      - TLS_PATH=/secure/tls.cert
      - MACAROON_PATH=/secure/admin.macaroon
      - REDIS_HOST=redis
      - GRPC_SSL_CIPHER_SUITES=HIGH+ECDSA
    ports:
      - '50078:50078'
    networks:
      - relayer
      - btcd
    command: bash -c 'npm i && npm start'

  # Mongo DB
  mongo:
    image: 'mongo:3.6.3'
    working_dir: '/home/db'
    ports:
      - '27017:27017'
    networks:
      - relayer

  # Redis
  redis:
    image: redis:4.0.9-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      - relayer


  # Extensions of the official LND docker build found here:
  #
  btcd:
    image: btcd
    build:
      context: ./
      dockerfile: docker/btcd/Dockerfile
    volumes:
      - shared:/rpc
      - bitcoin:/data
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - DEBUG
      - MINING_ADDRESS
    networks:
      btcd:
        aliases:
          - blockchain
          - rpcserver
    entrypoint: ["./start-btcd.sh"]

  btcctl:
    image: btcctl
    build:
      context: ./
      dockerfile: docker/btcd/Dockerfile
    volumes:
      - shared:/rpc
      - bitcoin:/data
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
    networks:
      - btcd
    entrypoint: ["./start-btcctl.sh"]

  # This is the btc node that relayer will interact with for the LND Engine
  lnd_btc:
    image: lnd
    build:
      context: ./
      dockerfile: docker/lnd/Dockerfile
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - CHAIN
      - DEBUG
    networks:
      - btcd
    volumes:
      - 'shared:/rpc'
      - 'secure:/secure/'
    expose:
      - '10009'
    entrypoint: ["./start-lnd.sh"]

# This information was taken from the LND docker setup (found in ./docker)
#
volumes:
  redis-data:
  secure:
  shared:
  bitcoin:

networks:
  relayer:
  btcd:
