version: '2.4'

services:
  # Kinesis Relayer
  relayer:
    build:
      context: ./docker
      dockerfile: relayer/Dockerfile
    working_dir: '/home/app'
    volumes:
      - './:/home/app'
      - 'shared:/shared'
    depends_on:
      - mongo
      - redis
      - lnd_btc
    environment:
      # - GRPC_VERBOSITY=INFO
      # - GRPC_TRACE=all
      - NODE_PATH=.
      - RELAYER_GRPC_HOST=0.0.0.0:28492
      - MONGODB_CONNECTION_URL=mongodb://mongo/relayer
      - LND_HOST=lnd_btc:10009
      - LND_TLS_CERT=/shared/lnd-engine-tls.cert
      - LND_MACAROON=/shared/lnd-engine-admin.macaroon
      - REDIS_HOST=redis
      - GRPC_SSL_CIPHER_SUITES=HIGH+ECDSA
    ports:
      - '28492:28492'
    expose:
      - '28492'
    networks:
      - relayer
      - lnd
    entrypoint: bash -c 'npm rebuild grpc && npm start'

  # Mongo DB
  mongo:
    image: 'mongo:3.6.3'
    working_dir: '/home/db'
    # TODO: this is only a development setting so you can view the DB from a UI
    #   like mongo compass
    ports:
      - '27017:27017'
    networks:
      - relayer

  # Redis
  redis:
    image: redis:4.0.9-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - /data
    networks:
      - relayer
    sysctls:
      net.core.somaxconn: '511'

  lnd_btc:
    extends:
      file: ./docker/lnd-docker-compose.yml
      service: lnd_btc
    build:
      context: ./docker
    depends_on:
      - btcd
    # Port configuration required to setup the correct interal/external ports
    # of the relayers LND engine
    ports:
      - '10111:10111'
    environment:
      - LISTEN=0.0.0.0:10111
      - EXTERNAL_ADDRESS=docker.for.mac.host.internal:10111
      - RPC_HOST=docker.for.mac.host.internal

  btcd:
    extends:
      file: ./docker/lnd-docker-compose.yml
      service: btcd
    build:
      context: ./docker
    ports:
    # ONLY USED DURING DEV TO PREVENT SETTING PORTS ON HOST
    # ports:
    #   - '10111:10111'
    ports:
      - '18555:18555' # simnet p2p
      - '18556:18556' # simnet rpc


volumes:
  shared:
  # These volumes are used in lnd/btc
  lnd:
  bitcoin:

networks:
  relayer:
  lnd:
