version: "2"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/app
    expose:
      - "8081"
    command: bash -c "npm i && npm start"
