version: '3'

services:
  # Kinesis Relayer
  relayer:
    image: 'node:8'
    working_dir: '/home/app'
    volumes:
      - './:/home/app'
      - 'secure:/secure/'
    depends_on:
      - mongo
      - redis
      - lnd_btc
    environment:
      # - GRPC_VERBOSITY=INFO
      # - GRPC_TRACE=all
      - NODE_PATH=.
      - RELAYER_GRPC_HOST=0.0.0.0:28492
      - MONGODB_CONNECTION_URL=mongodb://mongo/relayer
      - LND_HOST=lnd_btc:10009
      - TLS_CERT_PATH=/secure/tls.cert
      - LND_MACAROON_PATH=/secure/admin.macaroon
      - REDIS_HOST=redis
      - GRPC_SSL_CIPHER_SUITES=HIGH+ECDSA
    ports:
      - '28492:28492'
    expose:
      - '28492'
    networks:
      - relayer
    command: bash -c 'npm i && npm start'

  # Mongo DB
  mongo:
    image: 'mongo:3.6.3'
    working_dir: '/home/db'
    # TODO: this is only a development setting so you can view the DB from a UI
    #   like mongo compass
    ports:
      - '27017:27017'
    networks:
      - relayer

  # Redis
  redis:
    image: redis:4.0.9-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      - relayer


  # Extensions of the official LND docker build found here:
  #
  btcd:
    build:
      context: ./
      dockerfile: docker/btcd/Dockerfile
    volumes:
      - shared:/rpc
      - bitcoin:/data
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - DEBUG
      - MINING_ADDRESS
    networks:
      relayer:
        aliases:
          - blockchain
          - rpcserver
    entrypoint: ["./start-btcd.sh"]

  # This is the lnd/btc node specifically for relayer
  #
  lnd_btc:
    build:
      context: ./
      dockerfile: docker/lnd/Dockerfile
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - CHAIN
      - DEBUG
    networks:
      - relayer
    volumes:
      - 'shared:/rpc'
      - 'secure:/secure/'
    expose:
      - '10009'
    entrypoint: ["./start-lnd.sh"]

# This information was taken from the LND docker setup (found in ./docker)
#
volumes:
  redis-data:
  secure:
  shared:
  bitcoin:

networks:
  relayer:
