# we need to use DC v2 in order to support `extends`. Version 3 does not support
# extends (https://github.com/moby/moby/issues/31101) yet.

version: '2'

services:

  # Relayer BB
  relayer:
    container_name: 'relayer'
    image: 'node:8'
    user: 'node'
    working_dir: '/home/app'
    volumes:
      - './:/home/app'
    depends_on:
      - mongo
      - redis
    environment:
      - GRPC_HOST=0.0.0.0
      - GRPC_PORT=50078
      - MONGODB_CONNECTION_URL=mongodb://mongo:27017/relayer
      - LND_URL=localhost:10009
      - REDIS_HOST=redis
    expose:
      - '50078'
    ports:
      - '50078:50078'
    command: bash -c 'npm i && npm start'

  # Mongo DB
  mongo:
    container_name: mongo
    image: 'mongo:3.6.3'
    working_dir: '/home/db'
    expose:
      - '27017'
    ports:
      - '27018:27017'

  # Redis
  redis:
    container_name: redis
    image: redis:4.0.9-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  # LND multi-swap
  # @author kinesis
  lnd_btc_ltc:
    image: lnd_btc_ltc
    build:
      context: ./
      dockerfile: docker-multichain/lnd-multichain/Dockerfile
    container_name: lnd_btc_ltc
    environment:
      - CHAINA
      - CHAINB
      - DEBUG
      - NETWORK
      - RPCUSERA
      - RPCPASSA
      - RPCUSERB
      - RPCPASSB
      - HOST
    volumes:
      - shared:/rpc
      - lnd:/lnd
    networks:
      - multiswap
    ports:
      - "9735:9735"
    entrypoint: ["./start-lnd-multichain.sh"]

  # Extensions of the official LND docker build found here:
  # You can use `npm run build-lnd-docker` to update the LND docker files
  #
  # BTC
  #
  btc:
    container_name: btc
    extends:
      file: ./docker/docker-compose.yml
      service: btc

  btcd:
    extends:
      file: ./docker/docker-compose.yml
      service: btcd
    networks:
      btcd:
        aliases:
          - blockchain
          - rpcserver
      multiswap:
        aliases:
          - blockchaina

  # We are missing a few containers from the LND file because we cannot use extends w/ links,
  # so we have decided to port the following containers over to this file:
  # - btcctl
  # - lnd_btc
  #
  btcctl:
    extends: btc
    container_name: btcctl
    entrypoint: ["./start-btcctl.sh"]
    networks:
      - btcd

  lnd_btc:
    extends: lnd
    container_name: lnd_btc
    networks:
      - btcd

  # LTC
  #
  ltc:
    container_name: ltc
    extends:
      file: ./docker/docker-compose.yml
      service: ltc
  ltcd:
    extends:
      file: ./docker/docker-compose.yml
      service: ltcd
    networks:
      ltcd:
        aliases:
          - blockchain
          - rpcserver
      multiswap:
        aliases:
          - blockchainb
  lnd:
    container_name: lnd
    extends:
      file: ./docker/docker-compose.yml
      service: lnd

  # We are missing a few containers from the LND file because we cannot use extends w/ links,
  # so we have decided to port the following containers over to this file:
  # - ltcctl
  # - lnd_ltc
  ltcctl:
    extends: ltc
    container_name: ltcctl
    entrypoint: ["./start-ltcctl.sh"]
    networks:
      - ltcd

  lnd_ltc:
    extends: lnd
    container_name: lnd_ltc
    networks:
      - ltcd


# This information was taken from the LND docker setup (found in ./docker)
# AND can be very very brittle.
# We need these volumes because there is not
volumes:
  redis-data:
  bitcoin:
    driver: local
  shared:
    driver: local
  litecoin:
    driver: local
  kinesis:
    driver: local
  lnd:
    driver: local

networks:
  ltcd:
  btcd:
  multiswap:
