version: '3'

services:
  # Kinesis Relayer
  relayer:
    build:
      context: ./
      dockerfile: docker/kinesis/Dockerfile
    working_dir: '/home/app'
    volumes:
      - './:/home/app'
      - 'shared:/shared'
    depends_on:
      - mongo
      - redis
    environment:
      # - GRPC_VERBOSITY=INFO
      # - GRPC_TRACE=all
      - NODE_PATH=.
      - RELAYER_GRPC_HOST=0.0.0.0:28492
      - MONGODB_CONNECTION_URL=mongodb://mongo/relayer
      - LND_HOST=lnd_btc:10009
      - TLS_CERT_PATH=/secure/lnd-engine-tls.cert
      - LND_MACAROON_PATH=/shared/lnd-engine-admin.macaroon
      - REDIS_HOST=redis
      - GRPC_SSL_CIPHER_SUITES=HIGH+ECDSA
    ports:
      - '28492:28492'
    expose:
      - '28492'
    networks:
      - relayer
      - lnd
    command: bash -c 'npm start'

  # Mongo DB
  mongo:
    image: 'mongo:3.6.3'
    working_dir: '/home/db'
    # TODO: this is only a development setting so you can view the DB from a UI
    #   like mongo compass
    ports:
      - '27017:27017'
    networks:
      - relayer

  # Redis
  redis:
    image: redis:4.0.9-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - /data
    networks:
      - relayer

# This information was taken from the LND docker setup (found in ./docker)
#
volumes:
  shared:

networks:
  relayer:
  lnd:
