services:
  # LND multi-swap
  # @author kinesis
  lnd_btc_ltc:
    image: lnd_btc_ltc
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: lnd_btc_ltc
    environment:
      - CHAINA
      - CHAINB
      - DEBUG
      - NETWORK
      - RPCUSERA
      - RPCPASSA
      - RPCUSERB
      - RPCPASSB
      - HOST
    volumes:
      - shared:/rpc
      - lnd:/lnd
    networks:
      - multiswap
    ports:
      - "9735:9735"
    entrypoint: ["./start-lnd-multichain.sh"]

volumes:
  lnd:

networks:
  multiswap:
